name: Publish rolling build

on:
  push:
    branches:
      - master

env:
  REPO: '${{ github.repository }}'

jobs:
  docker:
    runs-on: ${{ matrix.os }}

    permissions:
      packages: write
      contents: read

    strategy:
      fail-fast: false
      matrix:
        arch: ["amd64"]
        include:
          - arch: amd64
            os: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Tag rolling release
        run: |
          cat BUILD.bazel | sed s/-jc+master/-jc+`date +%s`-`git rev-parse --short HEAD`/ | sed s/100master/`date +%s`.`git rev-parse --short HEAD`/ > BUILD.versioned
          cat BUILD.versioned
          mv BUILD.versioned BUILD.bazel

      # - name: Set up QEMU
      #   run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image identity
        id: image_id
        run: echo ::set-output name=ID::${GITHUB_REPOSITORY,,}

      - name: Publish to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/${{ matrix.arch }}
          push: true
          tags: |
            ghcr.io/${{ steps.image_id.outputs.ID }}:${{ github.ref_name }}-${{ matrix.arch }}

      - name: Extract built rTorrent artifacts from Docker image
        run: |
          docker buildx build --platform linux/${{ matrix.arch }} --target build -o type=tar . > ../out.tar
          tar xvf ../out.tar root/rtorrent/dist

      - name: Prepare distribution archive
        run: |
          mkdir dist-${{ matrix.arch }}
          cp doc/rtorrent.rc doc/rtorrent@.service root/rtorrent/dist/rtorrent dist-${{ matrix.arch }}

      - uses: actions/upload-artifact@v2
        with:
          name: rtorrent-linux-${{ matrix.arch }}
          path: dist-${{ matrix.arch }}/*

      - uses: actions/upload-artifact@v2
        with:
          name: rtorrent-deb-${{ matrix.arch }}
          path: root/rtorrent/dist/rtorrent-deb.deb